id: IC73ADF31
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:04:28+00:00'
last_modified: '2022-06-07T22:14:32.716284+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20454
  title: རྨ་ལྷོའི་དམངས་ཁྲོད་རིག་གནས་དཔེ་ཚོགས་གསེར་གྱི་ཐང་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1BE3:
      image_group_id: I8LS20456
      title: ''
      total_pages: 578
      order: 1
      base_file: 1BE3.txt
    1ABF:
      image_group_id: I8LS20457
      title: ''
      total_pages: 536
      order: 2
      base_file: 1ABF.txt
    '6824':
      image_group_id: I8LS20458
      title: ''
      total_pages: 425
      order: 3
      base_file: 6824.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
